// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[] = "fe0a0eba-26a3-4578-bb2c-ce807b544ef7";

const char SSID[] = "TP-Link-VR";    // Network SSID (name)
const char PASS[] = "Tewarit10";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = "X4ABWQMB3UF9J83LZYUQ";    // Secret device password

void onTriggerLevelChange();

float current_Temp;
float currrent_Humid;
int current_Moisture;
int trigger_Level;
bool pump_Status;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(current_Temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(currrent_Humid, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(current_Moisture, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trigger_Level, READWRITE, ON_CHANGE, onTriggerLevelChange);
  ArduinoCloud.addProperty(pump_Status, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
